# Generated by Django 5.1.5 on 2025-02-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
