# Generated by Django 5.1.5 on 2025-02-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
