# Generated by Django 5.1.5 on 2025-02-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_rename_user_employe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe_user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='employe.employe_user'),
        ),
    ]
