# Generated by Django 5.1.5 on 2025-02-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_alter_employe_user_reporting_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe_user',
            old_name='employee_id',
            new_name='id',
        ),
    ]
