# Generated by Django 5.1.5 on 2025-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskassignment_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
