# Generated by Django 5.1.5 on 2025-02-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_role_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
    ]
