# Generated by Django 5.1.5 on 2025-02-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_remove_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.role'),
        ),
    ]
